### ISSUE TITLE
設定 X-Frame-Options: SAMEORIGIN

### ISSUE THREAD

**Issue by danny50610** [HackerSir/CheckIn#161]
突然發現，是不是忘了設定 X-Frame-Options: SAMEORIGIN 啊

**Comment by jyhsu2000** [comment]
好像是... 
![image](https://user-images.githubusercontent.com/6276648/57273421-4e3f8080-70ca-11e9-8391-fcff7e77866f.png)

**Comment by jyhsu2000** [comment]
考慮到是專用主機
直接在 nginx 進行全域設定了
```
add_header X-Frame-Options SAMEORIGIN;
```

**Comment by danny50610** [comment]
也是可以從 nginx 下手啦
